DROP TABLE IF EXISTS USER_INFO CASCADE;
CREATE TABLE USER_INFO  (
	USER_ID BIGINT IDENTITY NOT NULL PRIMARY KEY AUTO_INCREMENT,
	FIRST_NAME VARCHAR(100) NOT NULL,
	LAST_NAME VARCHAR(100) NOT NULL,
	USER_NAME VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL
) ;
